export const products = [
  {
    id: 1,
    name: 'Minimalist Chair',
    category: 'Furniture',
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviews: 124,
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Black', hex: '#000000', image: 'chair-black' },
      { name: 'White', hex: '#ffffff', image: 'chair-white' },
      { name: 'Beige', hex: '#d4c5a9', image: 'chair-beige' },
    ],
    material: 'Wood',
    tags: ['bestseller', 'new'],
    images: ['chair-1', 'chair-2', 'chair-3'],
  },
  {
    id: 2,
    name: 'Ceramic Vase Set',
    category: 'Decor',
    price: 89,
    originalPrice: null,
    rating: 4.6,
    reviews: 89,
    sizes: ['Small', 'Medium', 'Large'],
    colors: [
      { name: 'Matte Black', hex: '#1a1a1a', image: 'vase-black' },
      { name: 'Terracotta', hex: '#c75b39', image: 'vase-terra' },
      { name: 'Sage', hex: '#87a878', image: 'vase-sage' },
    ],
    material: 'Ceramic',
    tags: ['bestseller'],
    images: ['vase-1', 'vase-2', 'vase-3'],
  },
  {
    id: 3,
    name: 'Designer Desk Lamp',
    category: 'Lighting',
    price: 149,
    originalPrice: 199,
    rating: 4.9,
    reviews: 203,
    sizes: ['One Size'],
    colors: [
      { name: 'Matte Black', hex: '#1a1a1a', image: 'lamp-black' },
      { name: 'Brushed Gold', hex: '#c9a96e', image: 'lamp-gold' },
      { name: 'Silver', hex: '#c0c0c0', image: 'lamp-silver' },
    ],
    material: 'Metal',
    tags: ['sale'],
    images: ['lamp-1', 'lamp-2', 'lamp-3'],
  },
  {
    id: 4,
    name: 'Wool Throw Blanket',
    category: 'Textiles',
    price: 179,
    originalPrice: null,
    rating: 4.7,
    reviews: 156,
    sizes: ['Standard', 'Oversized'],
    colors: [
      { name: 'Cream', hex: '#f5f5dc', image: 'throw-cream' },
      { name: 'Charcoal', hex: '#36454f', image: 'throw-charcoal' },
      { name: 'Rust', hex: '#b7410e', image: 'throw-rust' },
    ],
    material: 'Wool',
    tags: ['new'],
    images: ['throw-1', 'throw-2', 'throw-3'],
  },
  {
    id: 5,
    name: 'Modern Wall Clock',
    category: 'Decor',
    price: 129,
    originalPrice: null,
    rating: 4.5,
    reviews: 78,
    sizes: ['Small (30cm)', 'Large (50cm)'],
    colors: [
      { name: 'Walnut', hex: '#5c4033', image: 'clock-walnut' },
      { name: 'Oak', hex: '#c4a35a', image: 'clock-oak' },
      { name: 'Black', hex: '#000000', image: 'clock-black' },
    ],
    material: 'Wood',
    tags: [],
    images: ['clock-1', 'clock-2', 'clock-3'],
  },
  {
    id: 6,
    name: 'Artisan Plant Pot',
    category: 'Garden',
    price: 59,
    originalPrice: 79,
    rating: 4.4,
    reviews: 92,
    sizes: ['Small', 'Medium', 'Large'],
    colors: [
      { name: 'Terracotta', hex: '#c75b39', image: 'pot-terra' },
      { name: 'White', hex: '#ffffff', image: 'pot-white' },
      { name: 'Sage', hex: '#87a878', image: 'pot-sage' },
    ],
    material: 'Ceramic',
    tags: ['sale'],
    images: ['pot-1', 'pot-2', 'pot-3'],
  },
  {
    id: 7,
    name: 'Floating Coffee Table',
    category: 'Furniture',
    price: 449,
    originalPrice: 549,
    rating: 4.9,
    reviews: 187,
    sizes: ['Standard', 'Large'],
    colors: [
      { name: 'Walnut', hex: '#5c4033', image: 'table-walnut' },
      { name: 'Oak', hex: '#c4a35a', image: 'table-oak' },
      { name: 'White Oak', hex: '#e8dcc8', image: 'table-white' },
    ],
    material: 'Wood',
    tags: ['bestseller'],
    images: ['table-1', 'table-2', 'table-3'],
  },
  {
    id: 8,
    name: 'Floor Standing Mirror',
    category: 'Decor',
    price: 329,
    originalPrice: 429,
    rating: 4.8,
    reviews: 145,
    sizes: ['150cm', '180cm'],
    colors: [
      { name: 'Black Frame', hex: '#000000', image: 'mirror-black' },
      { name: 'Gold Frame', hex: '#c9a96e', image: 'mirror-gold' },
      { name: 'Natural', hex: '#c4a35a', image: 'mirror-natural' },
    ],
    material: 'Metal',
    tags: ['sale', 'new'],
    images: ['mirror-1', 'mirror-2', 'mirror-3'],
  },
  {
    id: 9,
    name: 'Linen Duvet Cover',
    category: 'Textiles',
    price: 199,
    originalPrice: null,
    rating: 4.7,
    reviews: 210,
    sizes: ['Twin', 'Queen', 'King'],
    colors: [
      { name: 'White', hex: '#ffffff', image: 'duvet-white' },
      { name: 'Stone', hex: '#a8a39d', image: 'duvet-stone' },
      { name: 'Blush', hex: '#de929c', image: 'duvet-blush' },
    ],
    material: 'Linen',
    tags: ['bestseller'],
    images: ['duvet-1', 'duvet-2', 'duvet-3'],
  },
  {
    id: 10,
    name: 'Pendant Light',
    category: 'Lighting',
    price: 249,
    originalPrice: 299,
    rating: 4.6,
    reviews: 98,
    sizes: ['Small', 'Medium', 'Large'],
    colors: [
      { name: 'Matte Black', hex: '#1a1a1a', image: 'pendant-black' },
      { name: 'Brass', hex: '#b5a642', image: 'pendant-brass' },
      { name: 'White', hex: '#ffffff', image: 'pendant-white' },
    ],
    material: 'Metal',
    tags: ['new', 'sale'],
    images: ['pendant-1', 'pendant-2', 'pendant-3'],
  },
  {
    id: 11,
    name: 'Handwoven Rug',
    category: 'Textiles',
    price: 389,
    originalPrice: null,
    rating: 4.8,
    reviews: 167,
    sizes: ['5x7ft', '8x10ft', '9x12ft'],
    colors: [
      { name: 'Natural', hex: '#c4a35a', image: 'rug-natural' },
      { name: 'Charcoal', hex: '#36454f', image: 'rug-charcoal' },
      { name: 'Terracotta', hex: '#c75b39', image: 'rug-terra' },
    ],
    material: 'Cotton',
    tags: [],
    images: ['rug-1', 'rug-2', 'rug-3'],
  },
  {
    id: 12,
    name: 'Oak Side Table',
    category: 'Furniture',
    price: 189,
    originalPrice: 229,
    rating: 4.5,
    reviews: 73,
    sizes: ['Standard'],
    colors: [
      { name: 'Natural Oak', hex: '#c4a35a', image: 'sidetable-natural' },
      { name: 'Dark Oak', hex: '#5c4033', image: 'sidetable-dark' },
      { name: 'White', hex: '#ffffff', image: 'sidetable-white' },
    ],
    material: 'Wood',
    tags: ['sale'],
    images: ['sidetable-1', 'sidetable-2', 'sidetable-3'],
  },
]

export const categories = ['All', 'Furniture', 'Decor', 'Lighting', 'Textiles', 'Garden']
export const materials = ['All', 'Wood', 'Metal', 'Ceramic', 'Wool', 'Linen', 'Cotton']
export const priceRanges = [
  { label: 'All', min: 0, max: Infinity },
  { label: 'Under $100', min: 0, max: 100 },
  { label: '$100 - $200', min: 100, max: 200 },
  { label: '$200 - $400', min: 200, max: 400 },
  { label: 'Over $400', min: 400, max: Infinity },
]
